POST localhost:8099/track/gpx
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="fileName"

GPX-Route
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="route.gpx"

< /home/pravussum/Nextcloud/gpx/2017%20Portugal%20Algarve/2017-09-30_21-45_Sat.gpx
--WebAppBoundary--

###

GET localhost:8099/track/1
###

GET localhost:8099/track/intersection
###